name: .NET Build & NuGet Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Check for code changes
        id: code-changes
        run: |
          if git diff --quiet HEAD^ HEAD -- '*.cs'; then
            echo "No code changes detected."
            echo "::set-output name=code-changes::false"
          else
            echo "Code changes detected."
            echo "::set-output name=code-changes::true"
          fi

      - name: Get current version
        id: get-version
        run: |
          current_version=$(grep -oP '(?<=<Version>)[^<]+' src/FideliusCrypto/FideliusCrypto.csproj)
          echo "Current version: $current_version"
          echo "::set-output name=current_version::$current_version"

      - name: Increment version
        id: increment-version
        run: |
          current_version=${{ steps.get-version.outputs.current_version }}
          IFS='.' read -r -a version_parts <<< "$current_version"
          new_version="${version_parts[0]}.${version_parts[1]}.$((version_parts[2] + 1))"
          echo "New version: $new_version"
          echo "::set-output name=new_version::$new_version"

      - name: Update version in .csproj
        run: |
          new_version=${{ steps.increment-version.outputs.new_version }}
          sed -i "s/<Version>.*<\/Version>/<Version>$new_version<\/Version>/" src/FideliusCrypto/FideliusCrypto.csproj
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add src/FideliusCrypto/FideliusCrypto.csproj
          git commit -m "Increment version to $new_version"
          git push

      - name: Restore dependencies
        if: steps.code-changes.outputs.code-changes == 'true'
        run: dotnet restore

      - name: Build
        if: steps.code-changes.outputs.code-changes == 'true'
        run: dotnet build --configuration Release --no-restore

      - name: Test
        if: steps.code-changes.outputs.code-changes == 'true'
        run: dotnet test --configuration Release --no-restore --verbosity normal

      - name: Pack NuGet Package
        if: steps.code-changes.outputs.code-changes == 'true'
        run: dotnet pack src/FideliusCrypto/FideliusCrypto.csproj --configuration Release --output nupkgs

      - name: Publish to NuGet
        if: github.ref == 'refs/heads/main' && steps.code-changes.outputs.code-changes == 'true'
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push "nupkgs/*.nupkg" --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate
